language: crystal
addons:
  apt:
    packages:
    - kcov

after_success:
  - crystal build --release spec/roman_spec.cr
  - kcov --exclude-pattern=/usr/share,/usr/include --coveralls-id=$TRAVIS_JOB_ID coverage ./roman_spec
